version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbus-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1obfxeq1hykq6"
s3_prefix = "eventbus-poc"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
